apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: chart-appset02
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/mteodor/helm-charts02
        revision: HEAD
        directories:
          - path: charts/*
  template:
    metadata:
      name: '{{.path.basename}}-02'
    spec:
      project: 3eb96a4d
      source:
        repoURL: https://github.com/mteodor/helm-charts02
        targetRevision: HEAD
        path: '{{.path.path}}'
      destination:
        name: cluster11
        namespace: '{{.path.basename}}-02'
      syncPolicy:
        automated:
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
        - Validate=true
        - PruneLast=false
